# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [53]:

# Step 2: Load the aviation dataset
file_path = r"C:\Users\ADMIN\Documents\moringa-school\model-2\Aviation_Data_cleaning\data\AviationData.csv"
df = pd.read_csv(
    file_path,
    encoding="cp1252",
    low_memory=False
)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

# Display the first five rows
display(df.head())
print('-'*40)
df.info()
print('-'*40)
missing_summary = pd.DataFrame({
    "Missing Values": df.isna().sum(),
    "Missing Percentage": (df.isna().mean() * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    by="Missing Percentage",
    ascending=False
)

display(missing_summary)
print('-'*40)
display(df.describe().T)
print('-'*40)
display(df.describe(include="all").T)
print('-'*40)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

Dataset loaded successfully!
Dataset shape: (88889, 31)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  str
 1   Investigation.Type      88889 non-null  str
 2   Accident.Number         88889 non-null  str
 3   Event.Date              88889 non-null  str
 4   Location                88837 non-null  str
 5   Country                 88663 non-null  str
 6   Latitude                34382 non-null  str
 7   Longitude               34373 non-null  str
 8   Airport.Code            50132 non-null  str
 9   Airport.Name            52704 non-null  str
 10  Injury.Severity         87889 non-null  str
 11  Aircraft.damage         85695 non-null  str
 12  Aircraft.Category       32287 non-null  str
 13  Registration.Number     87507 non-null  str
 14  Make                    88826 non-null  str
 15  Model                   88797 non-null  str
 16  Amateur.Built           88787 non-null  str
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  str
 19  FAR.Description         32023 non-null  str
 20  Schedule                12582 non-null  str
 21  Purpose.of.flight       82697 non-null  str
 22  Air.carrier             16648 non-null  str
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  str
 28  Broad.phase.of.flight   61724 non-null  str
 29  Report.Status           82505 non-null  str
 30  Publication.Date        75118 non-null  str
dtypes: float64(5), str(26)
memory usage: 39.5 MB
----------------------------------------

                        Missing Values  Missing Percentage
Schedule                         76307               85.85
Air.carrier                      72241               81.27
FAR.Description                  56866               63.97
Aircraft.Category                56602               63.68
Longitude                        54516               61.33
Latitude                         54507               61.32
Airport.Code                     38757               43.60
Airport.Name                     36185               40.71
Broad.phase.of.flight            27165               30.56
Publication.Date                 13771               15.49
Total.Serious.Injuries           12510               14.07
Total.Minor.Injuries             11933               13.42
Total.Fatal.Injuries             11401               12.83
Engine.Type                       7096                7.98
Report.Status                     6384                7.18
Purpose.of.flight                 6192                6.97
Number.of.Engines                 6084                6.84
Total.Uninjured                   5912                6.65
Weather.Condition                 4492                5.05
Aircraft.damage                   3194                3.59
Registration.Number               1382                1.55
Injury.Severity                   1000                1.12
Country                            226                0.25
Amateur.Built                      102                0.11
Model                               92                0.10
Make                                63                0.07
Location                            52                0.06
Accident.Number                      0                0.00
Investigation.Type                   0                0.00
Event.Id                             0                0.00
Event.Date                           0                0.00

----------------------------------------

,count,mean,std,min,25%,50%,75%,max
Number.of.Engines,82805.0,1.146585,0.446510,0.0,1.0,1.0,1.0,8.0
Total.Fatal.Injuries,77488.0,0.647855,5.485960,0.0,0.0,0.0,0.0,349.0
Total.Serious.Injuries,76379.0,0.279881,1.544084,0.0,0.0,0.0,0.0,161.0
Total.Minor.Injuries,76956.0,0.357061,2.235625,0.0,0.0,0.0,0.0,380.0
Total.Uninjured,82977.0,5.325440,27.913634,0.0,0.0,1.0,2.0,699.0

----------------------------------------

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Event.Id,88889,87951,20001214X45071,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Investigation.Type,88889,2,Accident,85015,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Accident.Number,88889,88863,ERA22LA103,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Event.Date,88889,14782,1982-05-16,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location,88837,27758,"ANCHORAGE, AK",434,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,88663,219,United States,82248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,34382,25589,332739N,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longitude,34373,27154,0112457W,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Airport.Code,50132,10374,NONE,1488,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Airport.Name,52704,24870,Private,240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Injury.Severity,87889,109,Non-Fatal,67357,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aircraft.damage,85695,4,Substantial,64148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aircraft.Category,32287,15,Airplane,27617,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Registration.Number,87507,79104,NONE,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Make,88826,8237,Cessna,22227,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Model,88797,12318,152,2367,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Amateur.Built,88787,2,No,80312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number.of.Engines,82805.0,NaN,NaN,NaN,1.146585,0.44651,0.0,1.0,1.0,1.0,8.0
Engine.Type,81793,12,Reciprocating,69530,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAR.Description,32023,31,091,18221,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Schedule,12582,3,NSCH,4474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purpose.of.flight,82697,26,Personal,49448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Air.carrier,16648,13590,Pilot,258,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total.Fatal.Injuries,77488.0,NaN,NaN,NaN,0.647855,5.48596,0.0,0.0,0.0,0.0,349.0
Total.Serious.Injuries,76379.0,NaN,NaN,NaN,0.279881,1.544084,0.0,0.0,0.0,0.0,161.0
Total.Minor.Injuries,76956.0,NaN,NaN,NaN,0.357061,2.235625,0.0,0.0,0.0,0.0,380.0
Total.Uninjured,82977.0,NaN,NaN,NaN,5.32544,27.913634,0.0,0.0,1.0,2.0,699.0
Weather.Condition,84397,4,VMC,77303,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Broad.phase.of.flight,61724,12,Landing,15428,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Report.Status,82505,17074,Probable Cause,61754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Publication.Date,75118,2924,25-09-2020,17019,NaN,NaN,NaN,NaN,NaN,NaN,NaN

----------------------------------------
Number of rows: 88889
Number of columns: 31

Column names:
['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date']

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [ ]:
# Inspecting the columns relevant to filtering aircraft and events

data_columns = [
    "Event.Date",
    "Investigation.Type",
    "Amateur.Built",
    "Aircraft.Category",
    "Make",
    "Model"
]

df[data_columns].head()

print('-'*40)

# Checking data types and missing values in the relevant columns

df[data_columns].info()

df[data_columns].isna().sum()

# Examining values to identify inconsistencies and possible imputations

for col in data_columns:
    print(f"\n {col} value counts:")
    print(df[col].value_counts(dropna=False).head())

print('-'*40)
# Standardizing aircraft category values

df["Aircraft.Category"] = df["Aircraft.Category"].replace({
    "UNK": np.nan,
    "Unknown": np.nan,
    "WSFT": "Weight-Shift",
    "ULTR": "Ultralight"
})

df["Aircraft.Category"].value_counts(dropna=False)

print('-'*40)
# Filling missing categories using the mode for each model

model_category_mode = (
    df.dropna(subset=["Model", "Aircraft.Category"])
      .groupby("Model")["Aircraft.Category"]
      .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
)

missing_category = df["Aircraft.Category"].isna()

df.loc[missing_category, "Aircraft.Category"] = (
    df.loc[missing_category, "Model"].map(model_category_mode)
)

df["Aircraft.Category"].isna().sum()
print('-'*40)
# Converting Event.Date to datetime

df["Event.Date"] = pd.to_datetime(
    df["Event.Date"],
    errors="coerce"
)

----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 54204 entries, 0 to 54203
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Event.Date          54204 non-null  str
 1   Investigation.Type  54204 non-null  str
 2   Amateur.Built       54204 non-null  str
 3   Aircraft.Category   54204 non-null  str
 4   Make                54204 non-null  str
 5   Model               54204 non-null  str
dtypes: str(6)
memory usage: 4.5 MB

 Event.Date value counts:
Event.Date
2000-07-08    23
1983-02-19    19
1983-10-01    19
1986-05-17    19
1983-06-26    18
Name: count, dtype: int64

 Investigation.Type value counts:
Investigation.Type
Accident    54204
Name: count, dtype: int64

 Amateur.Built value counts:
Amateur.Built
No    54204
Name: count, dtype: int64

 Aircraft.Category value counts:
Aircraft.Category
Airplane    54204
Name: count, dtype: int64

 Make value counts:
Make
CESSNA     24426
PIPER      13421
BEECH       4397
MOONEY      1170
GRUMMAN      976
Name: count, dtype: int64

 Model value counts:
Model
152          2199
172          1610
172N         1079
PA-28-140     890
172M          751
Name: count, dtype: int64
----------------------------------------
----------------------------------------
----------------------------------------

In [ ]:
# Filtering records according to the client's criteria

df = df[
    (df["Event.Date"] >= "1983-01-01") &
    (df["Investigation.Type"] == "Accident") &
    (df["Amateur.Built"] == "No") &
    (df["Aircraft.Category"] == "Airplane")
].copy()

df.head()
print('-'*40)

print("Rows and columns after filtering:", df.shape)

print("\nInvestigation types:")
print(df["Investigation.Type"].value_counts(dropna=False))

print("\nAmateur-built status:")
print(df["Amateur.Built"].value_counts(dropna=False))

print("\nAircraft categories:")
print(df["Aircraft.Category"].value_counts(dropna=False))

print("\nEarliest event date:", df["Event.Date"].min())

----------------------------------------
Rows and columns after filtering: (59415, 31)

Investigation types:
Investigation.Type
Accident    59415
Name: count, dtype: int64

Amateur-built status:
Amateur.Built
No    59415
Name: count, dtype: int64

Aircraft categories:
Aircraft.Category
Airplane    59415
Name: count, dtype: int64

Earliest event date: 1983-01-01 00:00:00

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [ ]:

injury_columns = [
    "Injury.Severity",
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]

# Displaying a few records to understand the data.
df[injury_columns].head(10)
print('-'*40)
# Checking which injury columns have missing values and their data types.
print("Missing values in each injury column:")
print(df[injury_columns].isna().sum())

print("\nData types:")
print(df[injury_columns].dtypes)
print('-'*40)
# Create a temporary estimate of fatal injuries using the severity label.
severity_fatal = (
    df["Injury.Severity"]
    .astype("string")
    .str.contains("Fatal", case=False, na=False)
)

reported_fatal = df["Total.Fatal.Injuries"]

# Comparing records where both sources provide enough information.
check_records = reported_fatal.notna() & df["Injury.Severity"].notna()

if check_records.sum() > 0:
    agreement = (
        (reported_fatal[check_records] > 0)
        == severity_fatal[check_records]
    ).mean()

    print(f"Agreement between severity and fatal counts: {agreement:.2%}")
else:
    print("There are not enough complete records to compare.")
print('-'*40)
# Only use the severity-based estimate if the agreement exceeds 99%.
if check_records.sum() > 0 and agreement > 0.99:

    # Estimating one or more fatalities when severity is marked as fatal.
    # For non-fatal severity labels, the estimate is zero.
    estimated_fatal = severity_fatal.astype(int)

    # Filling only missing fatal counts; preserve reported values.
    missing_fatal = df["Total.Fatal.Injuries"].isna()

    df.loc[missing_fatal, "Total.Fatal.Injuries"] = (
        estimated_fatal[missing_fatal]
    )

    print("Missing fatal injury counts have been filled.")
else:
    print(
        "Agreement did not exceed 99%. "
        "Review the severity labels before imputing fatal counts."
    )

print('-'*40)
# These four columns describe the different injury outcomes.
count_columns = [
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]

# Counting how many records have no injury information at all.
all_counts_missing = df[count_columns].isna().all(axis=1)

print("Records with all injury counts missing:", all_counts_missing.sum())

# Removing records where none of the four counts is available.
df = df.loc[~all_counts_missing].copy()
print('-'*40)
# Assumption: For records with at least one reported count,
# a blank in another injury-count column is treated as zero.

df[count_columns] = df[count_columns].fillna(0)

# Injury counts should be whole numbers, not decimals.
df[count_columns] = df[count_columns].astype(int)

# Confirming that no missing injury counts remain.
print(df[count_columns].isna().sum())
print(df[count_columns].dtypes)
print('-'*40)


df["Total.Passengers"] = df[count_columns].sum(axis=1)

# Inspecting the new column.
df[["Total.Passengers"] + count_columns].head(5)
print('-'*40)
# A meaningful injury fraction requires a positive total.
df = df[df["Total.Passengers"] > 0].copy()

print("Dataset shape after injury-count cleaning:", df.shape)
print('-'*40)
# Derived column: Fatal.Serious.Fraction
# A value close to 1 means a high proportion of people suffered
# fatal or serious injuries. A value close to 0 means a lower proportion.

df["Fatal.Serious.Fraction"] = (
    df["Total.Fatal.Injuries"] + df["Total.Serious.Injuries"]
) / df["Total.Passengers"]

# Displaying the results for a quick review.
df[
    [
        "Total.Fatal.Injuries",
        "Total.Serious.Injuries",
        "Total.Passengers",
        "Fatal.Serious.Fraction"
    ]
].head(5)
print('-'*40)
# Checking that the fraction is between 0 and 1.
print(
    "Fraction within the expected range:",
    df["Fatal.Serious.Fraction"].between(0, 1).all()
)

# Checking for missing values in the new columns.
print("\nMissing values in derived columns:")
print(
    df[["Total.Passengers", "Fatal.Serious.Fraction"]]
    .isna()
    .sum()
)

# Reviewing summarizwd statistics for the new metric.
df[["Total.Passengers", "Fatal.Serious.Fraction"]].describe()

----------------------------------------
Missing values in each injury column:
Injury.Severity            260
Total.Fatal.Injuries      7588
Total.Serious.Injuries    8401
Total.Minor.Injuries      7957
Total.Uninjured           3638
dtype: int64

Data types:
Injury.Severity               str
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
dtype: object
----------------------------------------
Agreement between severity and fatal counts: 23.52%
----------------------------------------
Agreement did not exceed 99%. Review the severity labels before imputing fatal counts.
----------------------------------------
Records with all injury counts missing: 40
----------------------------------------
Total.Fatal.Injuries      0
Total.Serious.Injuries    0
Total.Minor.Injuries      0
Total.Uninjured           0
dtype: int64
Total.Fatal.Injuries      int64
Total.Serious.Injuries    int64
Total.Minor.Injuries      int64
Total.Uninjured           int64
dtype: object
----------------------------------------
----------------------------------------
Dataset shape after injury-count cleaning: (59089, 32)
----------------------------------------
----------------------------------------
Fraction within the expected range: True

Missing values in derived columns:
Total.Passengers          0
Fatal.Serious.Fraction    0
dtype: int64

       Total.Passengers  Fatal.Serious.Fraction
count      59089.000000            59089.000000
mean           4.420501                0.279152
std           21.040668                0.432833
min            1.000000                0.000000
25%            1.000000                0.000000
50%            2.000000                0.000000
75%            2.000000                0.965714
max          576.000000                1.000000

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [ ]:

print("Damage categories:")
print(df["Aircraft.damage"].value_counts(dropna=False))

print("\nMissing values:")
print(df["Aircraft.damage"].isna().sum())

print('-'*40)
# Standardize the damage descriptions so that similar values are treated consistently.
df["Aircraft.damage"] = (
    df["Aircraft.damage"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Treating the  "Unknown" as missing information.
df["Aircraft.damage"] = df["Aircraft.damage"].replace({
    "Unknown": pd.NA,
    "Unk": pd.NA
})

# Removing records where the aircraft damage information is missing.
df = df.dropna(subset=["Aircraft.damage"]).copy()

# Checking the cleaned values.
print(df["Aircraft.damage"].value_counts(dropna=False))
print('-'*40)
# Creating a new column to track whether an aircraft was destroyed.
df["Aircraft.Destroyed"] = (
    df["Aircraft.damage"] == "Destroyed"
)

# Displaying the original damage category alongside the new indicator.
df[["Aircraft.damage", "Aircraft.Destroyed"]].head(10)
print('-'*40)
# Counting how many aircraft were destroyed and how many were not.

print("Aircraft destruction summary:")
print(df["Aircraft.Destroyed"].value_counts())

print("\nDestruction indicator as percentages:")
print(
    (df["Aircraft.Destroyed"].value_counts(normalize=True) * 100)
    .round(2)
)

Damage categories:
Aircraft.damage
Substantial    45575
Destroyed      12201
NaN              831
Minor            418
Unknown           64
Name: count, dtype: int64

Missing values:
831
----------------------------------------
Aircraft.damage
Substantial    45575
Destroyed      12201
Minor            418
Name: count, dtype: int64[pyarrow]
----------------------------------------
----------------------------------------
Aircraft destruction summary:
Aircraft.Destroyed
False    45993
True     12201
Name: count, dtype: int64[pyarrow]

Destruction indicator as percentages:
Aircraft.Destroyed
False    79.03
True     20.97
Name: proportion, dtype: double[pyarrow]

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

### Cleaning tasks for the Make column

1. **Inspect the column:** Check the number of missing values, unique manufacturers, and most frequent make names.
2. **Handle missing values:** Remove records with missing or blank manufacturer names because they cannot be reliably assigned to a manufacturer.
3. **Standardize text:** Remove leading and trailing spaces and convert manufacturer names to uppercase for consistency.
4. **Correct inconsistent labels:** Apply targeted replacements for known aliases and spelling variations so that the same manufacturer is not counted multiple times.
5. **Inspect manufacturer counts:** Check how frequently each manufacturer appears after cleaning.
6. **Filter uncommon manufacturers:** Keep manufacturers with at least 50 records to focus the analysis on makes with a reasonable amount of data.

**Assumption:** The threshold of 50 records is a practical choice for this analysis, not a claim that less frequent manufacturers are invalid. Filtering will reduce the scope of the analysis to more frequently recorded manufacturers.

In [ ]:

# Inspecting the manufacturer column before making changes.

print("Missing Make values:", df["Make"].isna().sum())
print("Unique Make values:", df["Make"].nunique())

print("\nTop 20 most common manufacturers:")
print(df["Make"].value_counts(dropna=False).head(20))

print("\nExamples of manufacturer names:")
print(df["Make"].dropna().unique()[:30])


# Removing unnecessary spaces and standardizing capitalization.
df["Make"] = (
    df["Make"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Treating
# Removing records without a known manufacturer.
df = df.dropna(subset=["Make"]).copy()

# Checking the result.
print("Missing Make values:", df["Make"].isna().sum())
print("Remaining rows:", len(df))
print("Unique manufacturers:", df["Make"].nunique())


# Displaying manufacturer names that may need closer inspection.
# Reviewing these examples before combining any labels.

make_counts = df["Make"].value_counts()

display(
    make_counts[make_counts.index.str.contains(
        r"CESSNA|PIPER|BEECH|BOEING|AIRBUS|MOONEY",
        case=False,
        regex=True
    )].head(50)
)


# Example structure for correcting verified manufacturer aliases.
# Add replacements only after confirming they are appropriate
# for your dataset and the project's cleaning procedure.

make_aliases = {
    # "VERIFIED VARIANT": "STANDARD MANUFACTURER NAME",
}

df["Make"] = df["Make"].replace(make_aliases)

# Checking the most frequent manufacturers after standardization.
print(df["Make"].value_counts().head(20))


# Counting the number of records for each manufacturer.
make_counts = df["Make"].value_counts()

# Keeping manufacturers represented by at least 50 records.
MIN_MAKE_COUNT = 50

common_makes = make_counts[
    make_counts >= MIN_MAKE_COUNT
].index

df = df[df["Make"].isin(common_makes)].copy()

# Reviewing the filtered dataset.
print("Minimum records per retained manufacturer:", MIN_MAKE_COUNT)
print("Remaining rows:", len(df))
print("Remaining unique manufacturers:", df["Make"].nunique())

print("\nTop 20 manufacturers after filtering:")
print(df["Make"].value_counts().head(20))

print("\nSmallest retained manufacturer counts:")
print(df["Make"].value_counts().sort_values().head(10))


# Confirming that no missing manufacturer names remain.
print("Missing Make values:", df["Make"].isna().sum())

# Confirming that every retained manufacturer meets the threshold.
final_make_counts = df["Make"].value_counts()

print(
    "All retained manufacturers meet the threshold:",
    (final_make_counts >= MIN_MAKE_COUNT).all()
)

# Reviewing the final dataset dimensions.
print("Final dataset shape:", df.shape)

Missing Make values: 1
Unique Make values: 1428

Top 20 most common manufacturers:
Make
Cessna            19768
Piper             10695
CESSNA             4662
Beech              3418
PIPER              2727
BEECH               979
Mooney              940
Grumman             900
Bellanca            765
Air Tractor         554
Boeing              462
Aeronca             390
Champion            387
Maule               351
Stinson             299
Aero Commander      277
Luscombe            272
Rockwell            267
Taylorcraft         266
De Havilland        252
Name: count, dtype: int64

Examples of manufacturer names:
<ArrowStringArray>
[                    'Cessna',                      'Piper',
             'North American',                      'Beech',
                 'Swearingen',                   'Canadair',
                       'Teal',                   'Bellanca',
                   'Luscombe',                     'Mooney',
                   'Champion',           'Grumman American',
                    'Douglas',             'Aero Commander',
 'Israel Aircraft Industries',                 'Mitsubishi',
                    'Stinson',                   'Rockwell',
                'Taylorcraft',                      'Maule',
                    'Aeronca',                     'Navion',
                    'Grumman',                      'Helio',
               'De Havilland',         'Eagle (ultralight)',
                 'Gulfstream',                       'Ryan',
                'Quicksilver',                 'Weedhopper']
Length: 30, dtype: str
Missing Make values: 0
Remaining rows: 58193
Unique manufacturers: 1153

Make
CESSNA                            24430
PIPER                             13422
BEECH                              4397
MOONEY                             1170
BOEING                              701
AIRBUS                               42
BOEING STEARMAN                      41
MOONEY AIRCRAFT CORP.                34
PIPER AIRCRAFT INC                   25
BEECHCRAFT                           23
CESSNA AIRCRAFT CO                   23
AIRBUS INDUSTRIE                     18
HAWKER BEECHCRAFT CORP               13
HAWKER BEECHCRAFT                    13
MOONEY AIRPLANE CO INC               10
PIPER AIRCRAFT CORPORATION           10
CESSNA AIRCRAFT COMPANY              10
CESSNA AIRCRAFT                      10
PIPER/CUB CRAFTERS                    7
CESSNA ECTOR                          6
PIPER AIRCRAFT                        6
HAWKER BEECHCRAFT CORPORATION         5
NEW PIPER AIRCRAFT INC                5
HAWKER BEECHCRAFT CORP.               4
NEW PIPER                             3
HAWKER-BEECHCRAFT                     3
PIPER AIRCRAFT, INC.                  3
HAWKER BEECH                          3
BEECH AIRCRAFT                        3
PIPER AEROSTAR                        2
BEECH AIRCRAFT CORPORATION            2
CESSNA/AIR REPAIR INC                 2
CESSNA ROBERTSON                      1
CESSNA REEMS                          1
CESSNA SOLOY                          1
BOEING - CANADA (DE HAVILLAND)        1
MOONEY AIRCRAFT CORP                  1
PIPER/STEVENS                         1
MOONEY AIRCRAFT                       1
PIPER CUB CRAFTERS                    1
BEECH AIRCRAFT CORP                   1
JETPROP DLX PIPER                     1
PIPER/WALLY'S FLYERS INC              1
HAWKER-BEECHCRAFT CORPORATION         1
BEECHCRAFT CORPORATION                1
PIPER PAWNEE                          1
MOONEY AIRPLANE COMPANY, INC.         1
REIMS-CESSNA                          1
BOEING-STEARMAN                       1
CESSNA/WEAVER                         1
Name: count, dtype: int64[pyarrow]

Make
CESSNA                24430
PIPER                 13422
BEECH                  4397
MOONEY                 1170
GRUMMAN                 976
BELLANCA                921
BOEING                  701
AIR TRACTOR             642
AERONCA                 539
MAULE                   495
CHAMPION                477
STINSON                 390
LUSCOMBE                364
AERO COMMANDER          344
TAYLORCRAFT             327
NORTH AMERICAN          300
ROCKWELL                289
DE HAVILLAND            281
AIR TRACTOR INC         216
CIRRUS DESIGN CORP      208
Name: count, dtype: int64[pyarrow]
Minimum records per retained manufacturer: 50
Remaining rows: 54215
Remaining unique manufacturers: 55

Top 20 manufacturers after filtering:
Make
CESSNA                24430
PIPER                 13422
BEECH                  4397
MOONEY                 1170
GRUMMAN                 976
BELLANCA                921
BOEING                  701
AIR TRACTOR             642
AERONCA                 539
MAULE                   495
CHAMPION                477
STINSON                 390
LUSCOMBE                364
AERO COMMANDER          344
TAYLORCRAFT             327
NORTH AMERICAN          300
ROCKWELL                289
DE HAVILLAND            281
AIR TRACTOR INC         216
CIRRUS DESIGN CORP      208
Name: count, dtype: int64[pyarrow]

Smallest retained manufacturer counts:
Make
GREAT LAKES                       53
AMERICAN CHAMPION AIRCRAFT        53
NAVION                            57
GRUMMAN ACFT ENG COR-SCHWEIZER    58
WSK PZL MIELEC                    63
RAYTHEON AIRCRAFT COMPANY         64
AMERICAN                          66
ROCKWELL INTERNATIONAL            67
CIRRUS DESIGN CORP.               67
FAIRCHILD                         69
Name: count, dtype: int64[pyarrow]
Missing Make values: 0
All retained manufacturers meet the threshold: True
Final dataset shape: (54215, 34)

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [ ]:

# Cleaning the Model column by removing unnecessary spaces.
df["Model"] = (
    df["Model"]
    .astype("string")
    .str.strip()
)

# Treating empty model names as missing values.
df["Model"] = df["Model"].replace("", pd.NA)

# Removing records without a model name.
df = df.dropna(subset=["Model"]).copy()

# Checking the results.
print("Missing model values:", df["Model"].isna().sum())
print("Remaining records:", len(df))


# Counting how frequently each model appears.
model_counts = df["Model"].value_counts()

print("Number of unique models:", df["Model"].nunique())

print("\nTop 20 most common models:")
print(model_counts.head(20))


# Counting the records for each manufacturer and model combination.
make_model_counts = (
    df.groupby(["Make", "Model"], dropna=False)
      .size()
      .reset_index(name="Record.Count")
      .sort_values("Record.Count", ascending=False)
)

print("Top 20 make/model combinations:")
display(make_model_counts.head(20))


# Counting how many different manufacturers use each model label.
makes_per_model = df.groupby("Model")["Make"].nunique()

# Finding model labels associated with more than one manufacturer.
shared_models = makes_per_model[makes_per_model > 1]

print("Model labels used by multiple manufacturers:", len(shared_models))

print("\nExamples of shared model labels:")
display(shared_models.sort_values(ascending=False).head(20))


# Standardizing manufacturer and model labels.
df["Make"] = df["Make"].astype("string").str.strip().str.upper()
df["Model"] = df["Model"].astype("string").str.strip().str.upper()

# Removing records without a manufacturer or model.
df = df.dropna(subset=["Make", "Model"]).copy()

# Replacing spaces within model names with hyphens.
df["Model"] = df["Model"].str.replace(r"\s+", "-", regex=True)

# Creating a combined aircraft-type identifier.
df["Make.Model"] = df["Make"] + "." + df["Model"]

# Inspecting the new column.
display(df[["Make", "Model", "Make.Model"]].head(10))

print("Unique aircraft types:", df["Make.Model"].nunique())



# Confirming that each identifier maps to one make and one model.
identifier_check = (
    df.groupby("Make.Model")[["Make", "Model"]]
      .nunique()
)

print(
    "Identifiers associated with multiple makes:",
    (identifier_check["Make"] > 1).sum()
)

print(
    "Identifiers associated with multiple models:",
    (identifier_check["Model"] > 1).sum()
)

Missing model values: 0
Remaining records: 54204
Number of unique models: 2089

Top 20 most common models:
Model
152          2199
172          1610
172N         1079
PA-28-140     856
172M          751
150           739
172P          659
182           602
180           593
150M          548
PA-18-150     547
PA-18         546
PA-28-180     544
PA-28-161     516
PA-28-181     500
150L          430
A36           420
G-164A        420
PA-38-112     417
140           383
Name: count, dtype: int64[pyarrow]
Top 20 make/model combinations:

        Make      Model  Record.Count
704   CESSNA        152          2199
717   CESSNA        172          1610
749   CESSNA       172N          1079
1951   PIPER  PA-28-140           856
748   CESSNA       172M           751
688   CESSNA        150           739
750   CESSNA       172P           659
781   CESSNA        182           602
767   CESSNA        180           592
703   CESSNA       150M           548
1903   PIPER  PA-18-150           547
1897   PIPER      PA-18           546
1957   PIPER  PA-28-180           544
1956   PIPER  PA-28-161           516
1959   PIPER  PA-28-181           500
702   CESSNA       150L           430
2021   PIPER  PA-38-112           417
341    BEECH        A36           400
685   CESSNA        140           383
716   CESSNA       170B           374

Model labels used by multiple manufacturers: 212

Examples of shared model labels:

Model
G-164A    6
500       5
G-164     5
G-164B    5
700       4
7ECA      4
S2R       4
S-2R      4
G-164C    4
8KCAB     4
7EC       4
7AC       4
400       3
500-S     3
7FC       3
7KCAB     3
402       3
7GCAA     3
690B      3
690A      3
Name: Make, dtype: int64

                Make       Model           Make.Model
3601          CESSNA        182P          CESSNA.182P
3602          CESSNA       182RG         CESSNA.182RG
3603          CESSNA        182P          CESSNA.182P
3604           PIPER  PA-28R-200     PIPER.PA-28R-200
3605          CESSNA         140           CESSNA.140
3607          CESSNA        340A          CESSNA.340A
3608  NORTH AMERICAN        T-6G  NORTH AMERICAN.T-6G
3609           PIPER   PA-24-250      PIPER.PA-24-250
3612           BEECH         A36            BEECH.A36
3613          CESSNA         180           CESSNA.180

Unique aircraft types: 2103
Identifiers associated with multiple makes: 0
Identifiers associated with multiple models: 0

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [ ]:
# Columns that may help explaining the outcome of an aviation accident
columns_to_inspect = [
    'Engine.Type',
    'Weather.Condition',
    'Number.of.Engines',
    'Purpose.of.flight',
    'Broad.phase.of.flight'
]

# Displaying data types, missing values, and unique values
for column in columns_to_inspect:
    print(f"\n{'=' * 40}")
    print(f"Column: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Missing values: {df[column].isna().sum()}")
    print(f"Number of unique values: {df[column].nunique(dropna=True)}")
    print(df[column].value_counts(dropna=False).head(20))

# Removing unnecessary spaces and standardizing capitalization
df['Engine.Type'] = df['Engine.Type'].apply(
    lambda value: value.strip().title()
    if isinstance(value, str) else value
)

# Checking the cleaned categories
print(df['Engine.Type'].value_counts(dropna=False))

# Standardizing the weather condition labels
df['Weather.Condition'] = df['Weather.Condition'].apply(
    lambda value: value.strip().upper()
    if isinstance(value, str) else value
)

# Inspecting the results
print(df['Weather.Condition'].value_counts(dropna=False))

# Converting the number of engines to a numeric data type
df['Number.of.Engines'] = pd.to_numeric(
    df['Number.of.Engines'],
    errors='coerce'
)

# Inspecting the values after conversion
print("Data type:", df['Number.of.Engines'].dtype)
print(df['Number.of.Engines'].value_counts(dropna=False).sort_index())

# Removing extra spaces and standardizing capitalization
df['Purpose.of.flight'] = df['Purpose.of.flight'].apply(
    lambda value: value.strip().title()
    if isinstance(value, str) else value
)

# Reviewing the cleaned categories
print(df['Purpose.of.flight'].value_counts(dropna=False).head(30))

# Standardizing the flight phase labels
df['Broad.phase.of.flight'] = df['Broad.phase.of.flight'].apply(
    lambda value: value.strip().title()
    if isinstance(value, str) else value
)

# Inspecting the cleaned categories
print(df['Broad.phase.of.flight'].value_counts(dropna=False))

# Reviewing the five columns after cleaning
print("Final column summary:")
display(df[columns_to_inspect].describe(include='all').T)

print("\nMissing values after cleaning:")
display(df[columns_to_inspect].isna().sum())

print("\nData types after cleaning:")
display(df[columns_to_inspect].dtypes)

========================================
Column: Engine.Type
Data type: str
Missing values: 2575
Number of unique values: 7
Engine.Type
Reciprocating    48546
NaN               2575
Turbo Prop        2065
Turbo Fan          516
Unknown            355
Turbo Jet          134
Turbo Shaft         12
UNK                  1
Name: count, dtype: int64

========================================
Column: Weather.Condition
Data type: str
Missing values: 1422
Number of unique values: 4
Weather.Condition
VMC    47964
IMC     4249
NaN     1422
UNK      454
Unk      115
Name: count, dtype: int64

========================================
Column: Number.of.Engines
Data type: float64
Missing values: 1893
Number of unique values: 5
Number.of.Engines
1.0    45785
2.0     6316
NaN     1893
0.0       78
3.0       70
4.0       62
Name: count, dtype: int64

========================================
Column: Purpose.of.flight
Data type: str
Missing values: 1990
Number of unique values: 24
Purpose.of.flight
Personal                     32830
Instructional                 7713
Aerial Application            3164
Unknown                       2710
Business                      2607
NaN                           1990
Positioning                    853
Other Work Use                 481
Ferry                          470
Aerial Observation             365
Executive/corporate            263
Public Aircraft                241
Skydiving                      164
Flight Test                    103
Banner Tow                      95
Public Aircraft - Federal       39
Glider Tow                      33
Public Aircraft - State         25
Firefighting                    15
Air Race show                   14
Name: count, dtype: int64

========================================
Column: Broad.phase.of.flight
Data type: str
Missing values: 14778
Number of unique values: 12
Broad.phase.of.flight
NaN            14778
Landing        10926
Takeoff         8075
Cruise          6491
Maneuvering     4302
Approach        4133
Taxi            1251
Climb           1237
Descent         1126
Go-around       1093
Standing         419
Unknown          324
Other             49
Name: count, dtype: int64
Engine.Type
Reciprocating    48546
NaN               2575
Turbo Prop        2065
Turbo Fan          516
Unknown            355
Turbo Jet          134
Turbo Shaft         12
Unk                  1
Name: count, dtype: int64
Weather.Condition
VMC    47964
IMC     4249
NaN     1422
UNK      569
Name: count, dtype: int64
Data type: float64
Number.of.Engines
0.0       78
1.0    45785
2.0     6316
3.0       70
4.0       62
NaN     1893
Name: count, dtype: int64
Purpose.of.flight
Personal                     32830
Instructional                 7713
Aerial Application            3164
Unknown                       2710
Business                      2607
NaN                           1990
Positioning                    853
Other Work Use                 481
Ferry                          470
Aerial Observation             365
Executive/Corporate            263
Public Aircraft                241
Skydiving                      164
Flight Test                    103
Banner Tow                      95
Public Aircraft - Federal       39
Glider Tow                      33
Public Aircraft - State         25
Firefighting                    15
Air Race Show                   14
Public Aircraft - Local         10
Air Race/Show                    9
Air Drop                         5
Pubs                             3
Asho                             2
Name: count, dtype: int64
Broad.phase.of.flight
NaN            14778
Landing        10926
Takeoff         8075
Cruise          6491
Maneuvering     4302
Approach        4133
Taxi            1251
Climb           1237
Descent         1126
Go-Around       1093
Standing         419
Unknown          324
Other             49
Name: count, dtype: int64
Final column summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Engine.Type,51629,7,Reciprocating,48546,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weather.Condition,52782,3,VMC,47964,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number.of.Engines,52311.0,NaN,NaN,NaN,1.12548,0.35001,0.0,1.0,1.0,1.0,4.0
Purpose.of.flight,52214,24,Personal,32830,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Broad.phase.of.flight,39426,12,Landing,10926,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Missing values after cleaning:

Engine.Type               2575
Weather.Condition         1422
Number.of.Engines         1893
Purpose.of.flight         1990
Broad.phase.of.flight    14778
dtype: int64

Data types after cleaning:

Engine.Type                  str
Weather.Condition            str
Number.of.Engines        float64
Purpose.of.flight            str
Broad.phase.of.flight        str
dtype: object

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [ ]:
# Calculating the number and percentage of missing values in each column
missing_summary = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing Percentage': (df.isnull().mean() * 100).round(2)
})

# Displaying columns with the most missing values first
missing_summary = missing_summary.sort_values(
    by='Missing Percentage',
    ascending=False
)

display(missing_summary)

# Setting the threshold for removing columns
missing_threshold = 70

# Identifying columns with more than 70% missing values
columns_to_drop = missing_summary[
    missing_summary['Missing Percentage'] > missing_threshold
].index.tolist()

print("Columns identified for removal:")
print(columns_to_drop)

print(f"\nNumber of columns to remove: {len(columns_to_drop)}")

# Reviewing the missing-value percentages of the identified columns
if columns_to_drop:
    display(missing_summary.loc[columns_to_drop])
else:
    print("No columns exceed the missing-value threshold.")


# Removing columns with more than 70% missing values
df.drop(columns=columns_to_drop, inplace=True)

# Confirming the updated dataframe dimensions
print("Updated dataframe shape:", df.shape)

# Checking missing values after column removal
remaining_missing = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing Percentage': (df.isnull().mean() * 100).round(2)
}).sort_values(by='Missing Percentage', ascending=False)

display(remaining_missing)

                        Missing Values  Missing Percentage
Schedule                         48782               90.00
Air.carrier                      45618               84.16
FAR.Description                  37874               69.87
Longitude                        33551               61.90
Latitude                         33545               61.89
Airport.Code                     21107               38.94
Airport.Name                     19563               36.09
Broad.phase.of.flight            14778               27.26
Publication.Date                  9161               16.90
Report.Status                     2719                5.02
Engine.Type                       2575                4.75
Purpose.of.flight                 1990                3.67
Number.of.Engines                 1893                3.49
Weather.Condition                 1422                2.62
Registration.Number                484                0.89
Country                             76                0.14
Location                            20                0.04
Event.Id                             0                0.00
Investigation.Type                   0                0.00
Accident.Number                      0                0.00
Model                                0                0.00
Aircraft.Category                    0                0.00
Amateur.Built                        0                0.00
Aircraft.damage                      0                0.00
Injury.Severity                      0                0.00
Event.Date                           0                0.00
Make                                 0                0.00
Total.Uninjured                      0                0.00
Total.Minor.Injuries                 0                0.00
Total.Serious.Injuries               0                0.00
Total.Fatal.Injuries                 0                0.00
Total.Passengers                     0                0.00
Fatal.Serious.Fraction               0                0.00
Aircraft.Destroyed                   0                0.00
Make.Model                           0                0.00

Columns identified for removal:
['Schedule', 'Air.carrier']

Number of columns to remove: 2

             Missing Values  Missing Percentage
Schedule              48782               90.00
Air.carrier           45618               84.16

Updated dataframe shape: (54204, 33)

                        Missing Values  Missing Percentage
FAR.Description                  37874               69.87
Longitude                        33551               61.90
Latitude                         33545               61.89
Airport.Code                     21107               38.94
Airport.Name                     19563               36.09
Broad.phase.of.flight            14778               27.26
Publication.Date                  9161               16.90
Report.Status                     2719                5.02
Engine.Type                       2575                4.75
Purpose.of.flight                 1990                3.67
Number.of.Engines                 1893                3.49
Weather.Condition                 1422                2.62
Registration.Number                484                0.89
Country                             76                0.14
Location                            20                0.04
Event.Id                             0                0.00
Event.Date                           0                0.00
Amateur.Built                        0                0.00
Model                                0                0.00
Make                                 0                0.00
Aircraft.Category                    0                0.00
Injury.Severity                      0                0.00
Aircraft.damage                      0                0.00
Investigation.Type                   0                0.00
Accident.Number                      0                0.00
Total.Uninjured                      0                0.00
Total.Minor.Injuries                 0                0.00
Total.Serious.Injuries               0                0.00
Total.Fatal.Injuries                 0                0.00
Total.Passengers                     0                0.00
Fatal.Serious.Fraction               0                0.00
Aircraft.Destroyed                   0                0.00
Make.Model                           0                0.00

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [ ]:
# Saving the cleaned dataframe to a CSV file
df.to_csv('aviation_accidents_cleaned.csv', index=False)

print("Cleaned dataframe saved successfully!")
# Checking the saved file by loading it back into a dataframe
df_check = pd.read_csv('aviation_accidents_cleaned.csv')

print("Original dataframe shape:", df.shape)
print("Saved dataframe shape:", df_check.shape)

# Displaying the first five rows
display(df_check.head())
import pandas as pd

df = pd.read_csv('aviation_accidents_cleaned.csv')

Cleaned dataframe saved successfully!

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8620\1841439068.py:6: DtypeWarning: Columns (0: Latitude, 1: Longitude, 2: Broad.phase.of.flight) have mixed types. Specify dtype option on import or set low_memory=False.
  df_check = pd.read_csv('aviation_accidents_cleaned.csv')

Original dataframe shape: (54204, 33)
Saved dataframe shape: (54204, 33)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Total.Passengers,Fatal.Serious.Fraction,Aircraft.Destroyed,Make.Model
0,20001214X42095,Accident,SEA83LA036,1983-01-01,"NEWPORT, OR",United States,NaN,NaN,ONP,NEWPORT MUNICIPAL,...,1,3,VMC,Approach,Probable Cause,NaN,4,0.0,False,CESSNA.182P
1,20001214X42067,Accident,MKC83LA056,1983-01-01,"WOODBINE, IA",United States,NaN,NaN,3YR,MUNICIPAL,...,0,2,VMC,Landing,Probable Cause,NaN,2,0.0,False,CESSNA.182RG
2,20001214X42063,Accident,MKC83LA050,1983-01-01,"MARYVILLE, MO",United States,NaN,NaN,78Y,RANKIN,...,0,1,VMC,Takeoff,Probable Cause,NaN,1,0.0,False,CESSNA.182P
3,20001214X42018,Accident,LAX83FUG11,1983-01-01,"UPLAND, CA",United States,NaN,NaN,CCB,CABLE,...,2,0,VMC,Approach,Probable Cause,NaN,2,0.0,False,PIPER.PA-28R-200
4,20001214X41951,Accident,CHI83LA074,1983-01-01,"SPRINGBROOK, WI",United States,NaN,NaN,NaN,SPRINGBROOK,...,0,2,VMC,Landing,Probable Cause,NaN,2,0.0,False,CESSNA.140

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8620\1841439068.py:15: DtypeWarning: Columns (0: Latitude, 1: Longitude, 2: Broad.phase.of.flight) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('aviation_accidents_cleaned.csv')